app:
  time-zone: Europe/Moscow

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timedb
    username: admin
    password: 12345
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 1000
        order_inserts: true
        order_updates: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    leon.task.timeindb.service.BatchWriterService: DEBUG
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
